### ISSUE TITLE
Test your skills: Selectors[选择器三]的问题

### ISSUE THREAD

**Issue by o0oo0ooo0** [bob1118/bob1118.github.io#1]
> 在本例中，尝试在不添加HTML的情况下进行以下更改。
> 
> - 链接文本的样式：使链接为橘色，被访问后变为绿色，当被hover时，移除链接文本的下划线。
> - **让容器里的第一个元素的字体大小为:150%，并且让这个元素的第一行是红色的。**
> - 让表格中每隔一行条带化，分别给它们一个颜色为#333的背景和一个白色前景。

你的CSS代码是
```
        .container p:first-child::first-line {
            font-size: 150%;
            color: red;
        }
```
这不符合

> **让容器里的第一个元素**的字体大小为:150%，并且让**这个元素的第一行**是红色的。

的要求, 我猜测需要分别写选择器, 就像这样

```
.container p:first-child {
    font-size: 150%;
}

.container p:first-child::first-line {
    color: red;
}
```

**Comment by bob1118** [comment]
感谢指出问题，已经在[fix mdn css selector test 3](https://github.com/bob1118/bob1118.github.io/commit/9718de560d09b603e1971b5b00a0d070bf1fea29)改正。
